name: adaptive_action_sheet
description: A Flutter package for action bottom sheet that adapts to the platform (Android/iOS).

version: 2.0.3
homepage: https://github.com/Daniel-Ioannou
repository: https://github.com/Daniel-Ioannou/flutter_adaptive_action_sheet

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.6.1
  
flutter:
  uses-material-design: true
